{% set name = "funcx" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/funcx-{{ version }}.tar.gz
  sha256: 77b3330beb795bd338b87d89700bd12136012dba0360e5293c3ef5d72b5a1e09

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - dill =0.3.5.1
    - funcx-common =0.0.25
    - globus-sdk >=3.14.0,<4
    - packaging >=21.1
    - pika >=1.2
    - python >=3.7
    - requests >=2.20.0
    - tblib =1.7.0
    - texttable >=1.6.7
    - typing_extensions >=4.0
    - websockets =10.3

test:
  imports:
    - funcx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/funcx-faas/funcx
  summary: 'funcX: High Performance Function Serving for Science'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WardLT
    - jan-janssen
